### ISSUE TITLE
Возможность выбора инстанции не из списка

### ISSUE THREAD

**Issue by l3nal3t0va** [NoPlagiarism/openvk-api#5]
я не особо шарю за питончик, но глядя на это кажется, что выбрать инстанцию можно только из списка.
Собсна думаю, что стоило бы дать возможность писать свой адрес инстанции
![изображение](https://user-images.githubusercontent.com/63073463/207640988-78c37052-3b01-4c3b-9431-501cada84b88.png)
по openvk.su стучаться бесполезно к слову

**Comment by NoPlagiarism** [comment]
```python
from openvk_api import OpenVkClient
vk = OpenVkClient(instance="notvk.com")
```

> по openvk.su стучаться бесполезно к слову

Знаю, разработка началась тогда, когда и по openvk.uk было бесполезно стучать, только http.
